---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Appendix 3: Descriptions of Account Pages, Sections, and Subsections {#sec-app3 .unnumbered}

In general, when you cannot find information on a given topic, please fill in that section with “Information needed” or “Information is needed” (not with “No information,” “No data,” or “Nothing known”). Similarly, use statements like “Additional information needed” instead of “No other information.” If you did not search for literature for a section(s), you may note “This section was not evaluated.” For sections or subsections in which there might not ever be any relevant information for a species because the behavior does not apply (e.g., Nonbreeding Nests, Cooperative Breeding, or Brood Parasitism by Other Species), use “Not reported.”

Please avoid using the words “recent” or “recently” in accounts. This is a relative term, and some accounts are updated more frequently than others, which can lead to misleading statements in some cases. Please try to provide the relevant year (or range of years) whenever possible.

## [INTRODUCTION]{style="color:purple;"} {#sec-app3-intro}

All accounts should include a concise introduction of 1–5 paragraphs. Introduce your species to the reader, emphasizing aspects that make it unique, including (as appropriate) systematics, appearance, distribution, migration, habitat, foraging, breeding, population size, and conservation. The best introductions are not simply a summary of factual details but strive for readability while still reflecting the science within the account. Descriptions of appearance should be concise and are generally not the focus of the Introduction. Descriptions of range should be general (e.g., occurs in montane forests of Tanzania and Kenya, typically from 2,600–3,400 m). Introductions generally do not include cited references unless a quote is included or information that is not cited elsewhere in the account is presented. Some accounts have summarized aspects of the species that are well studied, providing citations, especially at the end of the Introduction.

## [FIELD IDENTIFICATION]{style="color:purple;"} {#sec-app3-id}

### [Field Identification (introduction)]{style="color:blue;"} {#sec-app3-id-intro}

If the Identification article is particularly long, summarize the most important aspects of the identification of the species, including the essential field marks. A bulleted list may be appropriate here.

### [Identification]{style="color:blue;"} {#sec-app3-id-id}

Provide a general summary description of the major points of identification for adults and juveniles by sex (when age and sex can be determined). The terms “adults” or “first-cycle birds” can be used here, but be sure to include the plumage(s) in parentheses following the terms, as listed under Plumages. “Juveniles” can be used for birds in Juvenile Plumage without the need for the extra term. Include separate descriptions for adults in Definitive Basic and Definitive Alternate Plumages if they differ (or state that they are similar if an alternate plumage occurs and is similar in appearance to basic plumage). After adults of each sex and plumage are described, briefly describe Juvenile, Formative (usually), and all other predefinitive plumages in about one sentence each. When appropriate, discussion of subspecies, notable morphs or color variants, or otherwise unique populations can be briefly included.

The diagnosis should be scientific rather than that of a field guide, but it should also be easy to read and digest by novices. Stress features of size, shape, color, or structure that can be recognized on birds in the field. Give the overall (general) length and mass of live birds, accompanied by a statement of relative size compared to related species if useful for identification (e.g., a medium-sized hummingbird). Report any differences in length, mass, or plumage between males and females. Keep this section succinct. Detailed descriptions of size, color, etc., will be called for in other sections. No subsections are needed for this section.

### [Similar Species Summary]{style="color:blue;"} {#sec-app3-id-sssum}

If the Similar Species section is of substantial length (5+ paragraphs), please use the Similar Species Summary to briefly summarize the key issues. Avoid too much repetition with Similar Species, however.

### [Similar Species]{style="color:blue;"} {#sec-app3-id-ss}

Summarize the major points of identification that distinguish your species from any closely related or otherwise similar species. Cite any recent papers that thoroughly discuss how to distinguish your species from similar species in the field, but do not include references to standard field guides. Identification among subspecies (or morphs, variants, etc.) may also be briefly included here, although any detailed description of subspecies appearance should be included in the Subspecies section on the Systematics page. Keep this section succinct. Detailed descriptions of size, color, etc., will be called for in other sections. No subsections are needed for this section.

## [PLUMAGES, MOLTS, AND STRUCTURE]{style="color:purple;"} {#sec-app3-plumages}

### [Plumages]{style="color:blue;"} {#sec-app3-plumages-plumages}

x

### [Molts]{style="color:blue;"} {#sec-app3-plumages-molts}

x

### [Bare Parts]{style="color:blue;"} {#sec-app3-plumages-bare}

x

### [Measurements]{style="color:blue;"} {#sec-app3-plumages-measurements}

Linear Measurements

x

Mass

x

## [SYSTEMATICS]{style="color:purple;"} {#sec-app3-systematics}

### [Systematics History]{style="color:blue;"} {#sec-app3-systematics-history}

x

### [Geographic Variation]{style="color:blue;"} {#sec-app3-systematics-geographic}

x

### [Subspecies]{style="color:blue;"} {#sec-app3-systematics-subspecies}

x

### [Related Species]{style="color:blue;"} {#sec-app3-systematics-related}

x

### [Hybridization]{style="color:blue;"} {#sec-app3-systematics-hybrid}

x

### [Fossils]{style="color:blue;"} {#sec-app3-systematics-fossils}

x

## [DISTRIBUTION]{style="color:purple;"} {#sec-app3-distribution}

x

### [Distribution (introduction)]{style="color:blue;"} {#sec-app3-distribution-intro}

x

Breeding Range/Nonbreeding Range

x

Elevational Range

x

Introduced Range

x

Extralimital Records

x

### [Historical Changes to the Distribution]{style="color:blue;"} {#sec-app3-distribution-historical}

x

## [HABITAT]{style="color:purple;"} {#sec-app3-habitat}

### [Habitat (introduction)]{style="color:blue;"} {#sec-app3-habitat-intro}

x

### [General Habitat]{style="color:blue;"} {#sec-app3-habitat-general}

x

### [Habitat in Breeding Range]{style="color:blue;"} {#sec-app3-habitat-breeding}

x

### [Habitat in Migration]{style="color:blue;"} {#sec-app3-habitat-migration}

x

### [Habitat in Nonbreeding Range]{style="color:blue;"} {#sec-app3-habitat-nonbreeding}

x

## [MOVEMENTS AND MIGRATION]{style="color:purple;"} {#sec-app3-movements}

### [Movements and Migration (introduction)]{style="color:blue;"} {#sec-app3-movements-intro}

x

### [Dispersal and Site Fidelity]{style="color:blue;"} {#sec-app3-movements-dispersal}

x

### [Nonmigratory Movements]{style="color:blue;"} {#sec-app3-movements-nomigratory}

x

### [Migration Overview]{style="color:blue;"} {#sec-app3-movements-overview}

x

### [Timing and Routes of Migration]{style="color:blue;"} {#sec-app3-movements-timing}

x

### [Migratory Behavior]{style="color:blue;"} {#sec-app3-movements-behavior}

x

### [Control and Physiology of Migration]{style="color:blue;"} {#sec-app3-movements-control}

x

## [DIET AND FORAGING]{style="color:purple;"} {#sec-app3-diet}

x

### [Diet and Foraging (introduction)]{style="color:blue;"} {#sec-app3-diet-intro}

x

### [Feeding]{style="color:blue;"} {#sec-app3-diet-feeding}

**Microhabitat for Foraging**

x

**Food Capture and Consumption**

x

### [Diet]{style="color:blue;"} {#sec-app3-diet-diet}

**Major Food Items**

x

**Quantitative Analysis**

x

### [Food Selection and Storage]{style="color:blue;"} {#sec-app3-diet-storage}

x

### [Nutrition and Energetics]{style="color:blue;"} {#sec-app3-diet-nutrition}

x

### [Metabolism and Temperature Regulation]{style="color:blue;"} {#sec-app3-diet-metabolism}

x

### [Drinking, Pellet Casting, and Defecation]{style="color:blue;"} {#sec-app3-diet-drinking}

x

## [SOUNDS AND VOCAL BEHAVIOR]{style="color:purple;"} {#sec-app3-sounds}

x

### [Sounds and Vocal Behavior (introduction)]{style="color:blue;"} {#sec-app3-sounds-intro}

x

### [Vocalizations]{style="color:blue;"} {#sec-app3-sounds-vocalizations}

**Vocal Development**

x

**Vocal Array**

x

**Geographic Variation**

x

**Phenology**

x

**Daily Pattern of Vocalizing**

x

**Places of Vocalizing**

x

**Sex Differences**

x

**Repertoire and Delivery of Songs**

x

**Social Context and Presumed Functions of Vocalizations**

x

### [Nonvocal Sounds]{style="color:blue;"} {#sec-app3-sounds-nonvocal}

x

## [BEHAVIOR]{style="color:purple;"} {#sec-app3-behavior}

x

### [Behavior (introduction)]{style="color:blue;"} {#sec-app3-behavior-intro}

x

### [Locomotion]{style="color:blue;"} {#sec-app3-behavior-locomotion}

x

### [Self-Maintenance]{style="color:blue;"} {#sec-app3-behavior-self}

x

### [Agonistic Behavior]{style="color:blue;"} {#sec-app3-behavior-agonistic}

x

### [Sexual Behavior]{style="color:blue;"} {#sec-app3-behavior-sexual}

x

### [Social and Interspecific Behavior]{style="color:blue;"} {#sec-app3-behavior-social}

x

### [Predation]{style="color:blue;"} {#sec-app3-behavior-predation}

x

## [BREEDING]{style="color:purple;"} {#sec-app3-breeding}

x

### [Breeding (introduction)]{style="color:blue;"} {#sec-app3-breeding-intro}

x

### [Phenology]{style="color:blue;"} {#sec-app3-breeding-phenology}

x

### [Nest Site]{style="color:blue;"} {#sec-app3-breeding-site}

x

### [Nest]{style="color:blue;"} {#sec-app3-breeding-nest}

x

### [Eggs]{style="color:blue;"} {#sec-app3-breeding-eggs}

x

### [Incubation]{style="color:blue;"} {#sec-app3-breeding-incubation}

x

### [Hatching]{style="color:blue;"} {#sec-app3-breeding-hatching}

x

### [Young Birds]{style="color:blue;"} {#sec-app3-breeding-young}

x

### [Parental Care]{style="color:blue;"} {#sec-app3-breeding-parental}

x

### [Cooperative Breeding]{style="color:blue;"} {#sec-app3-breeding-cooperative}

x

### [Brood Parasitism]{style="color:blue;"} {#sec-app3-breeding-parasitism}

x

### [Fledgling Stage]{style="color:blue;"} {#sec-app3-breeding-fledgling}

x

## [DEMOGRAPHY AND POPULATIONS]{style="color:purple;"} {#sec-app3-demography}

### [Demography and Populations (introduction)]{style="color:blue;"} {#sec-app3-demography-intro}

x

### [Measures of Breeding Activity]{style="color:blue;"} {#sec-app3-demography-measures}

x

### [Life Span and Survivorship]{style="color:blue;"} {#sec-app3-demography-life}

x

### [Pathogens and Parasites]{style="color:blue;"} {#sec-app3-demography-pathogens}

x

### [Causes of Mortality]{style="color:blue;"} {#sec-app3-demography-mortality}

x

### [Population Spatial Metrics]{style="color:blue;"} {#sec-app3-demography-spatial}

x

### [Population Status]{style="color:blue;"} {#sec-app3-demography-status}

x

### [Population Regulation]{style="color:blue;"} {#sec-app3-demography-regulation}

x

## [CONSERVATION AND MANAGEMENT]{style="color:purple;"} {#sec-app3-conservation}

### [Conservation Status]{style="color:blue;"} {#sec-app3-conservation-status}

x

### [Effects of Human Activity]{style="color:blue;"} {#sec-app3-conservation-effects}

x

### [Management]{style="color:blue;"} {#sec-app3-conservation-management}

x

## [RELATIONSHIP WITH HUMANS]{style="color:purple;"} {#sec-app3-humans}

### [Relationship with Humans (introduction)]{style="color:blue;"} {#sec-app3-humans-intro}

x

### [Vernacular Names]{style="color:blue;"} {#sec-app3-humans-vernacular}

x

### [Cultural, Symbolic, and Aesthetic Significance]{style="color:blue;"} {#sec-app3-humans-cultural}

**Early History**

x

**Presence in Folklore, Religion, and Symbolism**

x

**Depictions in Media**

x

**Public Perception**

x

### [Economic and Utilitarian Significance]{style="color:blue;"} {#sec-app3-humans-economic}

**Use by Humans**

x

**Harm Inflicted by Focal Species**

x

**Aviculture and Domestication**

x

**Use as a Research Model**

x

## [PRIORITIES FOR FUTURE RESEARCH]{style="color:purple;"} {#sec-app3-priorities}

## [OTHER]{style="color:purple;"} {#sec-app3-other}

## [ACKNOWLEDGMENTS]{style="color:purple;"} {#sec-app3-acknowledgments}

## [ABOUT THE AUTHOR(S)]{style="color:purple;"} {#sec-app3-authors}